# Site settings
title: "Brian's Way"
username: bcavagnolo
email: bcavagnolo@gmail.com
description: "This is where I capture bits of my stream of conciousness."
baseurl: ""
url: "http://bcavagnolo.github.io"

# Build settings
markdown: kramdown
permalink: pretty
